#!/bin/bash

# sudo aptitude install ethtool tp-smapi-dkms top powertop modconf
#
# usbcore.autosuspend=1 [kernel command]
#
# hal-disable-polling --device /dev/cdrom
#
# 
# 

if [ ! -f /sys/devices/platform/smapi/ac_connected ]; then
    exit 0
fi

STATUS=`cat /sys/devices/platform/smapi/ac_connected`

if [ "$STATUS" = "1" ]; then
    logger "On AC"

    iwconfig wlan0 power off

    sysctl -w vm.swappiness=60

    echo 5 > /sys/module/snd_hda_intel/parameters/power_save
    echo Y > /sys/module/snd_hda_intel/parameters/power_save_controller
    echo 1 > /dev/dsp

    echo 0 > /proc/sys/vm/laptop_mode
    echo 500 > /proc/sys/vm/dirty_writeback_centisecs

    for i in /sys/class/scsi_host/*; do
        echo max_performance > $i/link_power_management_policy
    done

    /etc/init.d/tor restart
    #/home/taro/.kde/Autostart/xflux.sh
    #/usr/local/dropbox/dropboxd &

else
    logger "On battery"

    # WiFi Card
    iwconfig wlan0 power on

    # Swappness
    sysctl -w vm.swappiness=10

    # Intel HD Audio
    echo 3 > /sys/module/snd_hda_intel/parameters/power_save
    echo Y > /sys/module/snd_hda_intel/parameters/power_save_controller
    echo 1 > /dev/dsp

    # Hard Drives
    echo 5 > /proc/sys/vm/laptop_mode
    echo 1500 > /proc/sys/vm/dirty_writeback_centisecs

    # SATA Link Power Management
    for i in /sys/class/scsi_host/*; do
        echo min_power > $i/link_power_management_policy
    done

    # USB Subsystems
    for i in /sys/bus/usb/devices/*/power/autosuspend; do
        echo 1 > $i
    done
    rmmod uhci_hcd

    # Disable Ethernet wake-up on LAN
    ethtool -s eth0 wol d
    ethtool -s eth0 autoneg off speed 100

    # Stop daemons less used.
    /etc/init.d/tor stop
    sleep 3
    kill -9 `pgrep knotify4`
    #kill -9 `pgrep xflux`
    #kill -9 `pgrep dropbox`

fi

